### ISSUE TITLE
Unable to link binaries...

### ISSUE THREAD

**Issue by tomalok** [metwork-framework/log_proxy#10]
I'm trying to build an Alpine Linux package for this, but it fails to link the binaries...  lots of "undefined reference" errors related to various glib2 things.

...however, per https://stackoverflow.com/questions/9966959/linker-errors-when-compiling-against-glib, the build is successful if `$(_LDFLAGS)` is moved to the *end* of the `gcc` line in `src/Makefile`.

**Comment by thefab** [comment]
Thanks! We are going to have a look at this. Is your package published somewhere? Maybe we can a link to it in the readme?

**Comment by tomalok** [comment]
I'll provide a PR with the fix, it's fairly simple.

Also, feedback from the Alpine main branch merger was "We should definitively report that upstream doesn't respect `DESTDIR=`", which supposedly is standard-ish these days?  I worked around that by doing...
```
make install PREFIX="$pkgdir/usr" BINARIES="log_proxy log_proxy_wrapper"
```
...in the `APKBUILD`'s `package()` declaration.

**Comment by thefab** [comment]
There is no difference between PREFIX and DESTDIR for this kind of little utility but, of course, we are open to have a more standard Makefile!

For your use case, I'm not familiar with `supervise-daemon` but it sounds a perfect use case. As we use a lot `log_proxy_wrapper` to capture log in another *process supervisor*: https://circus.readthedocs.io/en/latest/
