### ISSUE TITLE
wrapper makes fifo in /tmp

### ISSUE THREAD

**Issue by tomalok** [metwork-framework/log_proxy#13]
As I explore using this for rotating logs from `dockerd` which is managed by OpenRC's `supervise-daemon` process, I see that `log_proxy_wrapper` creates FIFOs in `/tmp` by default but is overridable via the TMPDIR env var.

It would be handy if this were also explicitly overridable via a command line option, as modifying the TMPDIR itself may have additional consequences for the command being wrapped.

**Comment by thefab** [comment]
sounds a good idea

@thebaptiste: can you add this please ? (`cli option> TMPDIR > /tmp`)

I propose `--fifo-tmp-dir` (`NULL` by default)

**Comment by thebaptiste** [comment]
Ok. I deal with it.

**Comment by thefab** [comment]
@tomalok: can you try this new feature? if this is ok for you, we will push a new release with it. thanks!

**Comment by tomalok** [comment]
sorry, i haven't had a chance to review this.  if it's working for you, it's probably good for a release.

**Comment by thefab** [comment]
just released in 0.3 (see `--fifo-tmp-dir` option)
