### ISSUE TITLE
problem when a maximum file size if set by ulimit

### ISSUE THREAD

**Issue by thefab** [metwork-framework/log_proxy#5]
and when logfiles are bigger than this limit, `log_proxy` crash:

```
write(5, "2020-03-11T09:39:30.064118Z     "..., 127) = -1 EFBIG (File too large)
--- SIGXFSZ {si_signo=SIGXFSZ, si_code=SI_USER, si_pid=18052, si_uid=500} ---
+++ killed by SIGXFSZ +++
```

http://man7.org/linux/man-pages/man2/getrlimit.2.html

we can catch `SIGXFSZ` limit and force a rotation in this case? But I think we will loose some logs in that case?

maybe we should **also** automatically reduce the rotation-size at the rlimit - 10% or something like that?

**Comment by thebaptiste** [comment]
Maybe we could check `ulimit -f` when log_proxy is run and force `--rotation-size` to 90% of this limit if it is set ?

**Comment by thefab** [comment]
- exactly, but we should do that in C inside `log_proxy`

maybe it should be enough and we can avoid to catch `SIGXFSZ`
